### ISSUE TITLE
Prevent iD Editor in restore page, dialog Leave page? doesn't work

### ISSUE THREAD

**Issue by AF-HAF-KARTOGRAF** [ideditor/schema-builder#145]
Please prevent iD Editor in restore page, I pressed by mistake F5 and dialog window Leave page? doesn't prevent from restoring page. Thanks

**Comment by tordans** [comment]
Hey @AF-HAF-KARTOGRAF it sounds like this is an issue for https://github.com/openstreetmap/id. I will close it here. Please add a new issue over there. Please add a step by step of what is wrong in your opinion and how it should behave, that will make it easier to understand your ticket.
