### ISSUE TITLE
presets.json - Let terms default to empty array

### ISSUE THREAD

**Issue by westnordost** [ideditor/schema-builder#2]
I'd like to propose to default `terms` for a `preset` to an empty array if it is not specified. Currently there are 4520 presets without terms in the [`presets.min.json`](https://raw.githubusercontent.com/openstreetmap/id-tagging-schema/main/dist/presets.min.json). Removing all these `"terms":[]` will reduce the `presets.min.json` by a bit.

**Comment by quincylvania** [comment]
@westnordost Sounds reasonable. Though we should also be better about adding terms to as many presets and fields as we can!

**Comment by westnordost** [comment]
Well, much stuff from NSI doesn't have terms

**Comment by bhousel** [comment]
> Well, much stuff from NSI doesn't have terms

Thats ok, we should remove all of NSI, so it can be released as a separate preset pack.
