### ISSUE TITLE
drop (now unused) icons for fields

### ISSUE THREAD

**Issue by tyrasd** [ideditor/schema-builder#30]
the current schema [allows `"icons"`](https://github.com/ideditor/schema-builder/blob/v4.0.4/schemas/field.json) to be specified for _fields_, but this property is not documented in the readme (nor anywhere else I can find). Are these icons meant to be used for anything or is it just perhaps just a leftover from the past or something similar? Anyway, this property should be either documented or dropped from the schema.

**Comment by bhousel** [comment]
more info here
 https://github.com/openstreetmap/id-tagging-schema/issues/314#issuecomment-1007669843
