### ISSUE TITLE
allow Röntgen icon set

### ISSUE THREAD

**Issue by tyrasd** [ideditor/schema-builder#75]
The [Röntgen](https://wiki.openstreetmap.org/wiki/R%C3%B6ntgen) [icon set](https://github.com/enzet/map-machine#r%C3%B6ntgen-icon-set) includes some potentially quite useful icons for presets. For example:

* ![](https://wiki.openstreetmap.org/w/images/9/9e/R%C3%B6ntgen_diving_platform.svg) for https://github.com/openstreetmap/id-tagging-schema/pull/637
* ![](https://wiki.openstreetmap.org/w/images/9/91/R%C3%B6ntgen_portal_crane.svg) and ![](https://wiki.openstreetmap.org/w/images/c/cf/R%C3%B6ntgen_gantry_crane.svg) for https://github.com/openstreetmap/id-tagging-schema/pull/649
* various icons for specific kinds of towers, traffic calming features, etc.
* maybe also field-value icons for  `roof:shape` https://github.com/openstreetmap/id-tagging-schema/issues/153, for the `design` field of power towers, etc.

Röntgen icons are licensed under a Creative Commons Attribution 4.0 International License.

**Comment by westnordost** [comment]
Err, where **are** the icons though? I didn't find them in the repo

**Comment by tyrasd** [comment]
Yeah, it's unfortunately not quite straight forward. Here's what I did for iD (https://github.com/openstreetmap/iD/commit/98e9a11a511179b24c8c0aa6f520a9ed372b1c55): [install](https://github.com/enzet/map-machine/blob/main/doc/INSTALL.md) map-machine, then run `map-machine icons` to generate the individual icons, then take the `icons_by_id` version of the resulting output. 

Alternatively, you could rely on iD's bundled copy at https://github.com/openstreetmap/iD/tree/develop/svg/roentgen – I will manually keep them up to date until a better solution is found.

//cc @enzet: It would be superbly nice to have a separate versioned package of just the pure icons, in order to use them more easily outside of map-machine. Do you think something like that would be feasible?

**Comment by tordans** [comment]
@tyrasd this reminds me of https://github.com/openstreetmap/id-tagging-schema/issues/314. Maybe this is a good reason to improve the documentation about how the whole icon stuff works from a dev but also from a content/"tagging"-contributor perspective.

**Comment by westnordost** [comment]
> Alternatively, you could rely on iD's bundled copy at https://github.com/openstreetmap/iD/tree/develop/svg/roentgen – I will manually keep them up to date until a better solution is found.

Thanks!

**Comment by tordans** [comment]
FYI I created https://github.com/enzet/map-machine/issues/149 to track the issues of having the icons more easily consumed. I think there was no issue, yet, and it sounds like that really should be easier.
