### ISSUE TITLE
replace `cycleway` with flexible `directionalCombo` field type

### ISSUE THREAD

**Issue by tyrasd** [ideditor/schema-builder#79]
See https://github.com/openstreetmap/iD/pull/9423 for more details and https://github.com/openstreetmap/id-tagging-schema/pull/674 for a possible first application of this new field.

**Comment by tyrasd** [comment]
One quite popular "directional" tag are `maxspeed:<direction>` with ~200k uses, but in order to support these also, the would need to be extended further, as the `maxspeed` field currently uses the special `roadspeed` field type.

Perhaps _directional_ should rather be an option which could be used with different field types?

**Comment by tordans** [comment]
> …as the `maxspeed` field currently uses the special `roadspeed` field type

Just for those of us, wo wondered what that looked like:

<img width="367" alt="image" src="https://user-images.githubusercontent.com/111561/209807835-590100a5-d33a-46c2-9e3d-87933719f815.png">

**Comment by tordans** [comment]
> One quite popular "directional" tag are `maxspeed:<direction>` with ~200k uses, but in order to support these also, the would need to be extended further, as the `maxspeed` field currently uses the special `roadspeed` field type.

I have a slightly different take: Exposing those tags is more important, than the fact that they have their own special field type. Why? If they are hidden, the chance of miss-tagging is higher than having them visible but a less convenient editing experience.

> Perhaps directional should rather be an option which could be used with different field types?

Looking at the fields features (https://github.com/ideditor/schema-builder#fields) that would require an additional layer / hierarchy, right?

Adding to my comment above, I would vote for first refactor the `cycleway` feature to be used with `parking`. And only then look into solving the `maxspeed` case. No need to do it all at once…

_Back on topic:_

We could also turn this round:
- The `directionCombo` is a `special` field
- And a field can have an additional, optional property of `unit` or `format`, which would be `format: "speed" | "height" | "colour"`. 
   One could even move more of the `type` values to the `format` like `"text" | "number" | "tel" | "url"`

What I don't like is, that the HTML "type" attribute has values like "tel", "color"; the current schema fits more into this pattern.

_Another take:_

Staying with our idea, to make add add a `wrapperType: "directional"` (or something like this). The "localized" field could be moved into this pattern as well. That would allow us to add "`description:de`" as a `type="textarea"` and `wrapperType="localized"`.
